const scanbridgeChatbot = document.createElement('script'); scanbridgeChatbot.src = 'chatbot.js'; document.head.append(scanbridgeChatbot);
const guideData = [
  { id:'xray', icon:'✦', source:'https://www.radiologyinfo.org/en/info/safety-radiation', en:{name:'X-ray', sub:'Quick pictures of bones, chest, and more', before:'Wear comfortable clothes. You may need to remove jewelry or metal items. Tell staff if pregnancy is possible.', during:'A technologist positions you and asks you to hold still. The images take only moments.', ask:'What part is being imaged? Do I need to remove anything? When will my clinician receive the report?'}, ar:{name:'الأشعة السينية', sub:'صور سريعة للعظام والصدر وغيرها', before:'ارتدِ ملابس مريحة. قد تحتاج إلى إزالة المجوهرات أو القطع المعدنية. أخبر الفريق إذا كان الحمل ممكناً.', during:'يضعك فني الأشعة في الوضع المناسب ويطلب منك الثبات. يستغرق التقاط الصور لحظات فقط.', ask:'أي جزء سيتم تصويره؟ هل أحتاج إلى إزالة شيء؟ متى سيحصل طبيبي على التقرير؟'} },
  { id:'ultrasound', icon:'⌁', source:'https://www.radiologyinfo.org/en/info/how-to-prepare-for-us-exam', en:{name:'Ultrasound', sub:'Sound-wave imaging with no ionizing radiation', before:'Preparation depends on the body area. Your center may ask you not to eat or drink, or to drink water and keep a full bladder.', during:'Gel is placed on the skin while a handheld probe moves over the area. Most exams are painless.', ask:'What preparation applies to my exam? Should I eat, drink, or arrive early?'}, ar:{name:'الألتراساوند', sub:'تصوير بالموجات الصوتية من دون إشعاع مؤين', before:'يعتمد التحضير على منطقة الجسم. قد يطلب منك المركز عدم الأكل أو الشرب، أو شرب الماء والاحتفاظ بمثانة ممتلئة.', during:'يوضع جل على الجلد ويحرك الفاحص مسباراً محمولاً فوق المنطقة. معظم الفحوصات غير مؤلمة.', ask:'ما التحضير المطلوب لفحصي؟ هل يجب أن آكل أو أشرب أو أصل مبكراً؟'} },
  { id:'ct', icon:'◌', source:'https://www.radiologyinfo.org/en/info/how-to-prepare-your-ct-exam', en:{name:'CT scan', sub:'Detailed, fast X-ray-based imaging', before:'Ask if contrast is planned. Follow food and drink instructions exactly. Tell staff about medicines, allergies, kidney conditions, and possible pregnancy.', during:'You lie on a table that moves through a short, donut-shaped scanner. Some CT scans use contrast.', ask:'Will I receive contrast? Do I need kidney tests? When will I get the report?'}, ar:{name:'التصوير المقطعي CT', sub:'تصوير سريع ومفصل يعتمد على الأشعة السينية', before:'اسأل إن كانت مادة التباين مخططة. اتبع تعليمات الطعام والشراب بدقة. أخبر الفريق عن الأدوية والحساسية وأمراض الكلى واحتمال الحمل.', during:'تستلقي على طاولة تتحرك داخل جهاز قصير يشبه الحلقة. تستخدم بعض فحوصات CT مادة تباين.', ask:'هل سأتلقى مادة تباين؟ هل أحتاج إلى فحوصات كلى؟ متى سيصدر التقرير؟'} },
  { id:'mri', icon:'◉', source:'https://www.radiologyinfo.org/en/info/how-to-prepare-for-mri-exam', en:{name:'MRI', sub:'Detailed imaging with a powerful magnet', before:'Complete the safety form carefully. Tell staff about every implant, device, surgery, metal fragment, or patch. Remove metal-containing items.', during:'You lie on a padded table. The scanner is loud, so ear protection is provided. Tell the center early about anxiety or claustrophobia.', ask:'Is my implant or device safe for MRI? Will I receive contrast? What support is available if I feel anxious?'}, ar:{name:'التصوير بالرنين MRI', sub:'تصوير تفصيلي باستخدام مغناطيس قوي', before:'أكمل استمارة السلامة بعناية. أخبر الفريق عن كل زرعة أو جهاز أو عملية أو شظية معدنية أو لصقة. أزل القطع التي تحتوي على معدن.', during:'تستلقي على طاولة مبطنة. الجهاز مرتفع الصوت، لذا يوفر المركز حماية للأذنين. أخبر المركز مبكراً بالقلق أو رهاب الأماكن المغلقة.', ask:'هل زرعتي أو جهازي آمن للرنين؟ هل سأتلقى مادة تباين؟ ما الدعم المتاح إذا شعرت بالقلق؟'} },
  { id:'contrast', icon:'◈', source:'https://www.radiologyinfo.org/en/info/safety-contrast', en:{name:'Contrast material', sub:'Sometimes used to make a scan clearer', before:'Tell your team about a previous contrast reaction, allergies, kidney disease, diabetes, thyroid or heart conditions, pregnancy, and breastfeeding questions.', during:'A small IV may be placed. Some people notice a temporary warm feeling or taste.', ask:'Which contrast will I receive? What should I do if I feel unwell after it?'}, ar:{name:'مادة التباين', sub:'تُستخدم أحياناً لجعل الفحص أوضح', before:'أخبر الفريق عن أي تفاعل سابق مع مادة تباين، أو حساسية، أو مرض كلى، أو سكري، أو مشاكل بالغدة الدرقية أو القلب، أو الحمل والرضاعة.', during:'قد توضع إبرة وريدية صغيرة. يلاحظ بعض الأشخاص إحساساً مؤقتاً بالدفء أو طعماً في الفم.', ask:'أي مادة تباين سأتلقى؟ ماذا أفعل إذا شعرت بتوعك بعدها؟'} },
  { id:'abdominal', icon:'⌁', source:'https://www.radiologyinfo.org/en/info/abdominus', en:{name:'Abdominal & gallbladder ultrasound', sub:'Ultrasound of the upper abdomen', before:'Confirm exact instructions. Some liver, gallbladder, spleen, or pancreas studies may require a fat-free meal the evening before and no food for 8–12 hours; other exams differ.', during:'Gel is placed on the abdomen while the probe moves across the area. You may change position or briefly hold your breath.', ask:'What preparation applies to my exact exam? Should I take my regular medicines?'}, ar:{name:'ألتراساوند البطن والمرارة', sub:'تصوير أعلى البطن بالألتراساوند', before:'تأكد من التعليمات الدقيقة. قد تتطلب بعض فحوص الكبد أو المرارة أو الطحال أو البنكرياس وجبة خالية من الدهون مساءً وعدم الأكل لمدة 8–12 ساعة؛ وتختلف فحوص أخرى.', during:'يوضع جل على البطن بينما يتحرك المسبار فوق المنطقة. قد تغير وضعيتك أو تحبس النفس لفترة قصيرة.', ask:'ما التحضير المطلوب لفحصي بالتحديد؟ هل أتناول أدويتي المعتادة؟'} }
];
const ui = { en:{home:'Home',eyebrow:'ScanPrep guides',title:'Clear answers before a scan.',intro:'Simple preparation guides for patients and families.',safety:'Safety note',safetyText:'Your doctor or imaging center’s instructions always come first. This information does not diagnose or replace medical care.',before:'Before you go',during:'What happens',ask:'Questions to ask',source:'Patient source',feedbackTitle:'Was this useful?',feedbackText:'Help us improve ScanPrep for patients and families.',feedbackButton:'Share feedback'}, ar:{home:'الرئيسية',eyebrow:'أدلة ScanPrep',title:'إجابات واضحة قبل الفحص.',intro:'أدلة بسيطة للاستعداد للمرضى والعائلات.',safety:'ملاحظة سلامة',safetyText:'تعليمات طبيبك أو مركز التصوير تأتي دائماً أولاً. هذه المعلومات لا تشخّص ولا تحل محل الرعاية الطبية.',before:'قبل الذهاب',during:'ماذا يحدث؟',ask:'أسئلة لطرحها',source:'مصدر للمريض',feedbackTitle:'هل كان هذا مفيداً؟',feedbackText:'ساعدنا في تحسين ScanPrep للمرضى والعائلات.',feedbackButton:'شاركنا رأيك'} };
let language = localStorage.getItem('scanbridge-language') || 'en';
const langButton = document.querySelector('.language-toggle'), themeButton = document.querySelector('.theme-toggle'), themeLabel = document.querySelector('.theme-label');
function setTheme(theme) { const dark=theme==='dark'; document.body.classList.toggle('dark-mode',dark); themeButton.setAttribute('aria-pressed',String(dark)); themeLabel.textContent=language==='ar'?(dark?'فاتح':'داكن'):(dark?'Light':'Dark'); localStorage.setItem('scanbridge-theme',theme); }
function render(){ const t=ui[language]; document.documentElement.lang=language; document.documentElement.dir=language==='ar'?'rtl':'ltr'; document.querySelectorAll('[data-ui]').forEach(e=>e.textContent=t[e.dataset.ui]); langButton.textContent=language==='ar'?'English':'العربية'; document.querySelector('#guide-list').innerHTML=guideData.map(g=>{const d=g[language];return `<details id="${g.id}" class="full-guide"><summary><span class="guide-symbol">${g.icon}</span><span><strong>${d.name}</strong><small>${d.sub}</small></span><b>+</b></summary><div class="guide-body"><div><h2>${t.before}</h2><p>${d.before}</p></div><div><h2>${t.during}</h2><p>${d.during}</p></div><div><h2>${t.ask}</h2><p>${d.ask}</p></div><a href="${g.source}" target="_blank" rel="noopener noreferrer">${t.source}: RadiologyInfo ↗</a></div></details>`}).join(''); }
document.querySelector('#guide-list').addEventListener('toggle',e=>{if(e.target.open)document.querySelectorAll('.full-guide[open]').forEach(card=>{if(card!==e.target)card.open=false;});},true);
langButton.addEventListener('click',()=>{language=language==='ar'?'en':'ar';localStorage.setItem('scanbridge-language',language);render();setTheme(localStorage.getItem('scanbridge-theme')||'light');});
themeButton.addEventListener('click',()=>setTheme(document.body.classList.contains('dark-mode')?'light':'dark'));
render();setTheme(localStorage.getItem('scanbridge-theme')||(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
