const scanbridgeChatbot = document.createElement('script'); scanbridgeChatbot.src = 'chatbot.js'; document.head.append(scanbridgeChatbot);
const ui = { ar: {
  home:'الرئيسية', eyebrow:'الإطلاق والأثر', title:'بُنيت ScanBridge بملاحظات أولية، وهي الآن متاحة لعدد أكبر من العائلات.', intro:'أنهت ScanBridge مرحلتها التجريبية الأولى وأصبحت متاحة للعامة. نوضح بصدق ما يمكن للخدمة فعله، وما يحتاج إلى تأكيد، وما نعمل على تحسينه.', centers:'منشأة مدرجة', centersNote:'مستويات تحقق مختلفة — أكّد بالاتصال', guides:'أدلة ScanPrep', guidesNote:'تحضير واضح يركز على المريض', languages:'لغتان متاحتان', languagesNote:'الإنجليزية والعربية', liveValue:'متاح', live:'إطلاق عام', liveNote:'الملاحظات تواصل توجيه التحديثات', pilotEyebrow:'من التجربة إلى الإطلاق العام', pilotTitle:'الخطوة التالية الواضحة مهمة أكثر عندما تكون المهمة الصحية مقلقة أصلاً.', pilotText:'ساعدنا الاختبار الأولي على مراجعة الرحلة الأساسية: فهم الفحص، العثور على مكان للاتصال به، إعداد بطاقة طوارئ، وسؤال مايلو من أين تبدأ. لا ننشر أعداد المشاركين أو تقييماتهم أو اقتباساتهم إلا إذا أمكن مشاركتها بشكل مجهول ومسؤول.', stepOne:'اقرأ دليلاً', stepOneText:'ابدأ بأسئلة التحضير بلغة بسيطة قبل الفحص.', stepTwo:'أكّد المركز', stepTwoText:'استخدم الدليل كنقطة بداية، ثم اتصل لتأكيد الخدمات والتوفر والتكلفة.', stepThree:'استخدم ملاحظاتك للتحسين', stepThreeText:'أخبرنا بما كان واضحاً أو ناقصاً أو صعب الاستخدام من دون مشاركة معلومات صحية خاصة.', resultsEyebrow:'الشفافية أولاً', resultsTitle:'لن نشارك دروس التجربة إلا كمعلومات مجهولة ومجمّعة.', resultsText:'لن تحوّل ScanBridge الحالة الصحية لأي شخص إلى قصة عامة. وإذا نشرنا دروساً من التجربة، فستكون استنتاجات عامة عن المنتج، لا بيانات شخصية أو تفاصيل طبية أو نتائج مختلقة.', partnerEyebrow:'للعائلات والمدارس والمراجعين', partnerTitle:'ساعدنا على إبقاء المعلومات واضحة ومسؤولة.', partnerText:'يمكنك الإبلاغ عن إدراج يحتاج إلى تحديث، أو مراجعة دليل ScanPrep، أو مشاركة ملاحظات عملية حول استخدام الموقع. يساعد ذلك ScanBridge على التحسن من دون تجاوز حدود النصيحة الطبية.', reviewGuides:'استكشف أدلة ScanPrep', shareThought:'شاركنا رأيك'
} };
let language = localStorage.getItem('scanbridge-language') || 'en'; const lang = document.querySelector('.language-toggle'), theme = document.querySelector('.theme-toggle'), themeLabel = document.querySelector('.theme-label');
document.querySelectorAll('[data-ui]').forEach(el => el.dataset.original = el.textContent);
function render(){ document.documentElement.lang=language==='ar'?'ar':'en'; document.documentElement.dir=language==='ar'?'rtl':'ltr'; document.querySelectorAll('[data-ui]').forEach(el=>el.textContent=language==='ar'?ui.ar[el.dataset.ui]:el.dataset.original); lang.textContent=language==='ar'?'English':'العربية'; const dark=document.body.classList.contains('dark-mode'); themeLabel.textContent=language==='ar'?(dark?'فاتح':'داكن'):(dark?'Light':'Dark'); }
function setTheme(value){const dark=value==='dark';document.body.classList.toggle('dark-mode',dark);theme.setAttribute('aria-pressed',String(dark));localStorage.setItem('scanbridge-theme',value);render();}
lang.addEventListener('click',()=>{language=language==='ar'?'en':'ar';localStorage.setItem('scanbridge-language',language);render();}); theme.addEventListener('click',()=>setTheme(document.body.classList.contains('dark-mode')?'light':'dark')); render(); setTheme(localStorage.getItem('scanbridge-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
